splish-webapp/config/routes.rb
Rails.application.routes.draw do
  # root to: 'root#root'
  root to: 'home#index'

  namespace :api, defaults: { format: :json } do
    resources :events
  end

  resources :guests, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

splish-webapp/app/models/event.rb
class Event < ActiveRecord::Base
  validates :owner_id, :location, :title, :description, presence: true

  has_and_belongs_to_many :guests

end

splish-webapp/app/models/guest.rb
class Guest < ActiveRecord::Base
  validates :email, :password_digest, :session_token, :first_name, :last_name, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_and_belongs_to_many :events

  def self.find_by_credentials(username, password)
    user = Guest.all.find_by(email: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end


  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

splish-webapp/app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :guest
  belongs_to :event
end

splish-webapp/app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController

  def index
    @events = Event.all
    render :index
  end

  def show
    @event = Event.find(params[:id])
    render :show
  end

  def new
    @event = Event.new
    render :new
  end

  def create
    data = JSON.parse(params.flatten()[0])
    data = (data["data"])
    @event = Event.new(data)
    if @event.save!
      Pusher.trigger('test_channel', 'my_event', {
        message: @event
      })

      head :ok, content_type: "text/html"
    else
      render json: @event.errors.full_messages, status: 422
    end
  end

  def edit
    @event = Event.find(params[:id])
    render :edit
  end

  def update
    @event = Event.find(params[:id])

    data = JSON.parse(params.flatten()[0])
    data = (data["data"])
    if (data["rsvp"])
      user_id = data["rsvp"]
      guest = Guest.find_by_id(user_id)
      @event.guests.push(guest) if @event.guests.include?(guest) == false
      guest.events.push(@event) if guest.events.include?(@event) == false
    elsif (data["dersvp"])
      user_id = data["dersvp"]
      guest = Guest.find_by_id(user_id)
      guest.events.delete(@event)
      @event.guests.delete(guest)
    else
      data.each do |k, v|
        if data[k] != nil
          @event[k] = data[k]
        end
      end
    end

    if @event.save()
      msg = @event
      msg = msg.as_json
      msg["guests"] = @event.guests.as_json

      Pusher.trigger('test_channel', 'eventUpdates', {
        message: msg
      })
      head :ok, content_type: "text/html"
    else
      render json: Event.new(listing_params).errors.full_messages, status: 422
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy if @event
    render :json => {}
  end

  private

    def listing_params
      params.require(:event).permit(:owner_id, :location, :start_date, :end_date, :description, :title)
    end

end

splish-webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    current_user ||= Guest.find_by_session_token(session[:session_token])
  end

  def sign_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def sign_out(user)
    session[:session_token] = nil
    user.reset_session_token!
  end

  def signed_in?
    !!current_user
  end

  def ensure_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

splish-webapp/app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    if signed_in?
      redirect_to "/#"
    else
      @guest = Guest.new
      render :new
    end
  end

  def create
    @guest = Guest.new(user_params)
    if @guest.save
      sign_in(@guest)
      redirect_to root_url
    else
      flash.now[:errors] = @guest.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:guest).permit(:email, :password, :first_name, :last_name)
  end
end

splish-webapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @events = Event.all
    # Pusher.trigger('test_channel', 'my_event', {
    #   message: 'test'
    # })
  end
end

splish-webapp/app/controllers/root_controller.rb
class RootController < ApplicationController
  # before_action :ensure_signed_in

  def root
  end
end

splish-webapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if signed_in?
      redirect_to root_url
    else
      render :new
    end
  end

  def create
    @guest = Guest.find_by_credentials(params[:guest][:email], params[:guest][:password])
    if @guest
      sign_in(@guest)
      redirect_to root_url
    else
      # redirect_to root_url
      flash.now[:errors] = ["Invalid username and/or password"]
      render :new
      # redirect_to root_url
    end
  end

  def destroy
    sign_out(current_user)
    redirect_to root_url
  end

end

splish-webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

splish-webapp/app/helpers/guests_helper.rb
module GuestsHelper
end

splish-webapp/app/views/events/edit.html.erb
<% redirect_to events_url unless current_user.id == @event.owner_id %>

<h2>Edit Your Event Listing</h2>
<br>
<form action="<%= event_url(@event.id) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="listing[owner_id]" value="<%= current_user.id %>">

  <label>Event title
  <input type="text" name="event[title]" value="<%= @event.title %>">
  </label><br>

  <label>Start Date
  <input type="date" name="event[start_date]" value="<%= @event.start_date %>">
  </label><br>

  <label>Age
  <input type="date" name="event[end_date]" value="<%= @event.end_date %>">
  </label><br>

  <label>Location
  <input type="text" name="event[location]" value="<%= @event.location %>">
  </label><br>

  <label>Description
    <textarea name="event[description]" rows="8" cols="40"><%= @event.body %></textarea>
  </label><br>

  <button name="Edit Listing">Edit Listing</button>

</form>

splish-webapp/app/views/events/new.html.erb
<form action="<%= events_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="event[owner_id]" value="<%= current_user.id %>">

  <label>Event title
  <input type="text" name="event[title]" value="<%= @event.title %>">
  </label><br>

  <label>Start Date
  <input type="date" name="event[start_date]" value="<%= @event.start_date %>">
  </label><br>

  <label>Age
  <input type="date" name="event[end_date]" value="<%= @event.end_date %>">
  </label><br>

  <label>Location
  <input type="text" name="event[location]" value="<%= @event.location %>">
  </label><br>

  <label>Description
    <textarea name="event[description]" rows="8" cols="40"><%= @event.body %></textarea>
  </label><br>

  <button name="Create New Event">Create New Event</button>

</form>

splish-webapp/app/views/guests/new.html.erb
<br>
<br>
<br>
<br>
<h1>Sign up</h1>
<div class="signup">
  <br>
  <br>
  <br>
  <br>
  <h2>Sign Up for a Splish Account</h2>
  <br>
  <br>

  <form  class="signupauth" action="<%= guests_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>E-mail:
    <input id="e-mail" type="text" name="guest[email]" placeholder="E-Mail Address" value="">
    </label>

    <label>First Name:
    <input id="First Name" type="text" name="guest[first_name]" placeholder="First Name" value="">
    </label>

    <label>Last Name:
    <input id="Last Name" type="text" name="guest[last_name]" placeholder="Last Name" value="">
    </label>

    <label>Password:
    <input id="Password" type="password" name="guest[password]" placeholder="Password" value="">
    </label>

    <br><br>
    <button class="signupbutton" name="Sign Up">Sign Up</button>

  </form>

  <br><br>
  <div class="signupauth">
    Already have an account? <strong><a href="/">Sign in at the top of our homepage</a></strong>
  </div>
</div>

splish-webapp/app/views/home/index.html.erb
<% content_for :header do  %>
  <%= render 'layouts/header' %>
<% end %>

<div class="eventstack-info hidden">
  <span>Each dot represents an event.<br>Click a dot to bring up an event.<br>Click it again to see more info about the event.</span>
</div>
<section id="eventstack-wrapper" class="eventstack hidden">
	<div>
		<figure ng-repeat="event in events" data-shuffle-iteration="2">
			<img src="https://unsplash.it/300/300?image={{event.id}}" alt="Image"/>
			<figcaption>
				<h2 class="eventstack-title">
        <span class="dates">
          <p ng-if="!(event.start_date == null || event.end_date == null)">From: {{event.start_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
          <p ng-if="!(event.start_date == null || event.end_date == null)">To: {{event.end_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
          <p class="eventstack-tbd" ng-if="event.start_date == null || event.end_date == null">TBD</p>
        </span>
          <span class="event-title">{{event.title}}</span>
        </h2>
				<div class="eventstack-back">
          <p ng-if="!(event.start_date == null || event.end_date == null)">From: {{event.start_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
          <p ng-if="!(event.start_date == null || event.end_date == null)">To: {{event.end_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
          <p class="eventstack-tbd" ng-if="event.start_date == null || event.end_date == null">TBD</p>
					<p>{{event.description}}</p>
          <p ng-if="!notTBDandPastEvent(event)"><span ng-show="notTBDandFutureEvent(event)">{{event.guests.length}} people have RSVP'd to this event.</span></p>
          <p ng-if="notTBDandPastEvent(event)">{{event.guests.length}} people attended this event.
            <br><br>
            This event ended {{daysSinceEnded(event.end_date)}} days ago.
            <br>
            <span ng-if="didAttendPastEvent(event)">You were there!</span>
          </p>
				</div>
			</figcaption>
		</figure>
	</div>
</section>

<div class="wrapper-wrapper">
  <div class="all-events">
    <div class="tbd-wrapper">
      <div ng-if="sortState === 'Sort by Event Title'" class="events" id="TBDevents" ng-repeat="event in events | filter: setFilterTBD" >
      	<ul class="">
      		<li class="scene" id="box-{{event.id}}">
      			<div class="box tbd-box">
      				<div class="front">
                <h1>{{event.title}}</h1>
                <img src="https://unsplash.it/300/300?image={{event.id}}" alt="Image"/>
                <p>
                  The date for this event is TBD.
                </p>
              </div>
      				<div class="info">
      					<header>
                  <p>{{event.description}}</p>
      					</header>
                <p>
                  The date for this event has not yet been set.
                </p>
                <p class="rsvp-count">{{event.guests.length}} people have RSVP'd to this event.</p>
                <div ng-if="user_id" class="rsvp-button">
                  <span ng-show={{user_id}}><md-button class="md-primary md-raised" ng-if="!(checkIfRSVPd(event.guests) || notTBDandPastEvent(event))" ng-click="rsvp($event, event.id)">
                    RSVP to this Event
                  </md-button></span>
                  <md-button class="md-primary md-raised" ng-if="checkIfEligibleToCancelEvent(event)" ng-click="dersvp($event, event.id)">
                    Cancel Your RSVP
                  </md-button>
                  <span ng-hide="notTBDandFutureEvent(event)">
                    <md-button ng-if="user_id == event.owner_id" ng-click="fillEditField(event)" class="md-primary md-raised" data-modal="modal-9">Edit Event</md-button>
                  </span>
                </div>
      				</div>
      			</div>
      		</li>
      	</ul>
      </div>
    </div>
    <div class="wrapper events event-wrapper" ng-repeat="event in events | filter: setFilter | orderBy:predicate:reverse" ng-if="!isTBD()" >
    	<ul class="">
    		<li class="scene" id="box-{{event.id}}">
    			<div class="box" >
    				<div class="front">
              <h1>{{event.title}}</h1>
              <img src="https://unsplash.it/300/300?image={{event.id}}" alt="Image"/>
              <p ng-if="!(event.start_date == null || event.end_date == null)" class="start-date">From: {{event.start_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
              <p ng-if="!(event.start_date == null || event.end_date == null)">To: {{event.end_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
              <p ng-if="event.start_date == null || event.end_date == null">TBD</p>
            </div>
    				<div class="info">
    					<header>
                <p>{{event.description}}</p>
    					</header>
              <p ng-if="!(event.start_date == null || event.end_date == null)">From: {{event.start_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
              <p ng-if="!(event.start_date == null || event.end_date == null)">To: {{event.end_date | date:'MMM d, yyyy \'at\' h:mm a'}}</p>
              <p ng-if="event.start_date == null || event.end_date == null">TBD</p>
              <p ng-if="!notTBDandPastEvent(event)"><span ng-show="notTBDandFutureEvent(event)">{{event.guests.length}} people have RSVP'd to this event.</span></p>
              <p ng-if="notTBDandPastEvent(event)">{{event.guests.length}} people attended this event.
                <br><br>
                This event ended {{daysSinceEnded(event.end_date)}} days ago.
                <br>
                <span ng-if="didAttendPastEvent(event)">You were there!</span>
              </p>
              <span ng-if="user_id">
                <md-button class="md-primary md-raised" ng-if="!(checkIfRSVPd(event.guests) || notTBDandPastEvent(event))" ng-click="rsvp($event, event.id)">
                RSVP to this Event
                </md-button>
                <md-button class="md-primary md-raised" ng-if="checkIfAttendingFutureEvent(event)" ng-click="dersvp($event, event.id)">
                  Cancel Your RSVP
                </md-button>
                <md-button ng-if="user_id == event.owner_id" ng-click="fillEditField(event)" class="md-primary md-raised" data-modal="modal-9">Edit Event</md-button>
              </span>
    				</div>
    			</div>
    		</li>
    	</ul>
    </div>

    </div>
  </div>

  <div class="md-modal md-effect-9" id="modal-9">
  	<div class="md-content">
  		<h3 class='modal-header'>create an event</h3>
  		<div>
        <section class="event-form">
          <form id="modal-form" name="messageForm" ng-submit="submitForm()" class="ang-form">
        	<span class="input input--styled">
        		<input ng-model="message.title" class="input__field input__field--styled" type="text" placeholder="What is your event called?" />
        		<label class="input__label input__label--styled">
        			<span class="input__label-content input__label-content--styled">Event Title</span>
        		</label>
        	</span>
          <span class="input input--styled" ng-model="message.description">
            <textarea class="input__field input__field--styled" name="description" ng-model="message.description" rows="8" cols="40" placeholder="Tell us more about your event...">
              Describe your event
            </textarea>
            <label class="input__label input__label--styled textarea" id="description">
              <span class="input__label-content input__label-content--styled">Description</span>
            </label>
          </span>

          <span class="input input--styled">
            <input id="autocompleteEdit" ng-model="message.location" class="input__field input__field--styled md-input" placeholder="Where is your event is taking place?" type="text" />
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">
                Location
              </span>
            </label>
          </span>

          <span class="input input--styled">
            <input mdc-datetime-picker="" class="input__field input__field--styled md-input" ng-model="message.start_date" short-time="true" date="true" time="true" type="text"
            placeholder="Start Date" max-date="dateTimeEnd" id="input_0" format="YYYY-MM-DD hh:mm a" />
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">
                Start Date/Time
              </span>
            </label>
          </span>
          <span class="input input--styled">
            <input mdc-datetime-picker="" short-time="true" class="input__field input__field--styled md-input" ng-model="message.end_date"  date="true" time="true" type="text"
            placeholder="End Date" min-date="dateTimeStart"="dateTimeEnd" id="input_1" format="YYYY-MM-DD hh:mm a" />
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">
                End Date/Time
              </span>
            </label>
          </span>
          <md-button type="submit" class="md-close md-primary md-raised">Submit</md-button>
        </form>
        </section>
  		</div>
  	</div>
  </div>
  <div class="md-modal md-effect-8" id="angular-triggered-modal">
  	<div class="md-content">
  		<h3 class='modal-header'>edit your event</h3>
  		<div>
        <section class="event-form">
          <form id="modal-form" name="messageForm" ng-submit="submitEditForm()" class="edit-modal-form">
        	<span class="input input--styled">
        		<input ng-model="message.title" class="input__field input__field--styled" type="text" placeholder="What is your event called?" />
        		<label class="input__label input__label--styled">
        			<span class="input__label-content input__label-content--styled">Event Title</span>
        		</label>
        	</span>
          <span class="input input--styled" ng-model="message.description">
            <textarea class="input__field input__field--styled" name="description" ng-model="message.description" rows="8" cols="40" placeholder="Tell us more about your event...">
              Describe your event
            </textarea>
            <label class="input__label input__label--styled textarea" id="description">
              <span class="input__label-content input__label-content--styled">Description</span>
            </label>
          </span>

          <span class="input input--styled">
            <input id="autocomplete" ng-model="message.location" class="input__field input__field--styled md-input" placeholder="Where is your event is taking place?" type="text" />
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">
                Location
              </span>
            </label>
          </span>

          <span class="input input--styled">
            <input mdc-datetime-picker="" class="input__field input__field--styled md-input" ng-model="message.start_date" short-time="true" date="true" time="true" type="text"
            placeholder="Start Date" max-date="dateTimeEnd" id="input_0" format="YYYY-MM-DD hh:mm a" />
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">
                Start Date/Time
              </span>
            </label>
          </span>
          <span class="input input--styled">
            <input mdc-datetime-picker="" short-time="true" class="input__field input__field--styled md-input" ng-model="message.end_date"  date="true" time="true" type="text"
            placeholder="End Date" min-date="dateTimeStart"="dateTimeEnd" id="input_1" format="YYYY-MM-DD hh:mm a" />
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">
                End Date/Time
              </span>
            </label>
          </span>
          <md-button type="submit" class="md-close md-primary md-raised">Submit</md-button>
        </form>
        </section>
  		</div>
  	</div>
  </div>

  <div class="md-overlay"></div>
</div>

splish-webapp/app/views/layouts/_errors.html.erb
<p style="color: #fff;">
  <%= flash.now[:errors].join('<br>').html_safe if flash.now[:errors] %>
</p>

splish-webapp/app/views/layouts/_header.html.erb
<div class="header_parent">
  <div class="header">
			<section class="content">
				<ul class="list">
					<li class="list__item list__item--burst color-12">
						<h3 class="list__text">SPLISH</h3>
						<button class="control__button control__button--play">
							<svg class="control__vector" aria-hidden="true" role="img" viewBox="0 0 24 24">
								<use xlink:href="#icon-play"></use>
							</svg>
						</button>
					</li>
				</ul>
			</section>
        <% if signed_in? %>
          <div class="authed" id="div-item-data" data-user-id="<%= current_user.id %>" >
        <% else %>
          <md-button ng-if="!user_id" class="md-trigger md-primary md-raised" data-modal="modal-1">Sign In</md-button>
        <% end %>
    </div>
    <div class="align">

    </div>
    <span ng-if="user_id" class="md-trigger add-event-button" data-modal="modal-9"><%= image_tag 'add.png' %></span>
  </div>

  <div class="md-modal md-effect-1" id="modal-1">
    <div class="md-content">
      <h3 class='modal-header'>Sign In</h3>
      <div>
        <div class="auth">
          <span class="guest-info">
          guest e-mail: johnsmith@example.com<br>
          guest password: testtest</span>
          <br>
          <form class='auth_form' action="<%= session_url %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <span class="input input--styled">
            <input type="text" class="input__field input__field--styled md-input" placeholder="E-Mail Address" name="guest[email]" value="">
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">E-mail:</span>
            </label>
          </span>
          <span class="input input--styled">
            <input id="password" type="password" class="input__field input__field--styled md-input" placeholder="Password" name="guest[password]" value="">
            <label class="input__label input__label--styled">
              <span class="input__label-content input__label-content--styled">
                Password:
              </span>
            </label>
          </span>

            <md-button type="submit" class="md-close md-primary md-raised" name="Sign In">Sign In</md-button>
          </form>
          <br>
          <section class='sign_in'>
            <span class="guest-info">Don't have an account yet?</span><br> <md-button class="md-close md-primary md-raised" onclick="window.location = './guests/new'" >Sign Up!</md-button>
          </section>
        </div>
      </div>
    </div>
  </div>

splish-webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splish</title>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-aria.min.js"></script>
    <link rel="stylesheet" href="https://material.angularjs.org/latest/angular-material.min.css"/>
    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMZms2er49ODMvfbXUtO5ADbAY-VYIpiA&libraries=places&callback=initAutocomplete" async defer></script> -->

    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body ng-app="splish" ng-controller="EventController" >
  <div class="menu-wrap">
		<nav class="menu-top">
			<div class="filter-list">
        <span class="hide-in-random-mode">
          <md-button ng-click="toggleSort(false); filter = 'tbd';" class="md-primary md-raised">See TBD Events</md-button><br>
          <md-button ng-click="toggleSort(false); filter = 'upcoming'" class="md-primary md-raised">See Upcoming Events</md-button><br>
          <md-button ng-click="toggleSort(false); filter = 'past'" class="md-primary md-raised">See Past Events</md-button><br>
          <md-button ng-click="toggleSort(false); filter = 'all'" class=" md-primary md-raised">See All Events</md-button><br>
          <md-button ng-click="toggleSort(false); filter = 'created'" class="md-primary md-raised">See Events You Created</md-button><br>
          <md-button ng-click="toggleSort(false); filter = 'rsvpd'" class=" md-primary md-raised">See RSVP'd Events</md-button><br>
          <md-button ng-click="toggleSort(true); filter = 'all';" class=" md-primary md-raised">{{sortState}}</md-button>
        </span>
        <md-button ng-click="toggleRandomMode()" class=" md-primary md-raised random-button">{{randomMode}}</md-button>
			</div>
		</nav>
		<button class="close-button" id="close-button"></button>
	</div>
  <button class="menu-button hidden" id="open-button">
  <%= image_tag 'filter-512.png' %></button>
	<div id="pagewrap" class="pagewrap content-wrap">
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMZms2er49ODMvfbXUtO5ADbAY-VYIpiA&libraries=places&callback=initAutocomplete"  defer></script>
    <%= render '/layouts/errors' %>
    <div class="container" id="page-content" class="content">
      <%= yield :header %>
      <%= yield %>
    </div>
    <div id="loader" class="pageload-overlay" data-opening="m -5,-5 0,70 90,0 0,-70 z m 5,35 c 0,0 15,20 40,0 25,-20 40,0 40,0 l 0,0 C 80,30 65,10 40,30 15,50 0,30 0,30 z">
			<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 80 60" preserveAspectRatio="none" >
				<path d="m -5,-5 0,70 90,0 0,-70 z m 5,5 c 0,0 7.9843788,0 40,0 35,0 40,0 40,0 l 0,60 c 0,0 -3.944487,0 -40,0 -30,0 -40,0 -40,0 z"/>
			</svg>
		</div>
  </div>
  </body>
</html>

splish-webapp/app/views/root/root.html.erb
<% content_for :header do  %>
  <%= render 'layouts/header' %>
<% end %>

<div id="content"></div>
<script type="text/javascript" charset="utf-8">

</script>